#!/usr/bin/env node

var path = require('path');
var shell = require('shelljs');
var execSync = require('child_process').execSync;
var packageRoot = path.join(__dirname, '../packages');

test('eslint-plugin-shopify');
test('chai-jscodeshift');
test('shopify-codemod');

function test(packageName) {
  var packagePath = path.join(packageRoot, packageName);
  shell.cd(packagePath);
  return execSync('npm test', {stdio: 'inherit'});
}
