import 'test-helper';
import removeTrailingElseUndefinedReturn from 'remove-trailing-else-undefined-return';

describe('removeTrailingElseUndefinedReturn', () => {
  it('removes void returns from else generated by Decaf', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/void');
  });
  it('removes argumentless returns from final else', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/removes-argumentless-else-return');
  });
  it('removes undefined returns from else generated by Decaf', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/undefined');
  });
  it('doesn\'t remove valid returns', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/valid');
  });
  it('doesn\'t remove the entire block in multi-lined blocks', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/multi');
  });
  it('ignores if-else with following statements', () => {
    expect(removeTrailingElseUndefinedReturn).to.transform('remove-trailing-else-undefined-return/ignores-if-else-with-following-statements');
  });
});
