import 'test-helper';
import removeEmptyCatchBlocks from 'remove-empty-catch-blocks';

describe('removeEmptyCatchBlocks', () => {
  it('removes empty catch blocks generated by Decaf', () => {
    expect(removeEmptyCatchBlocks).to.transform('remove-empty-catch-blocks/basic');
  });
});
