import 'test-helper';
import transform from 'remove-empty-catch-blocks';

describe('removeEmptyCatchBlocks', () => {
  it('removes empty catch blocks generated by Decaf', () => {
    expect(transform).to.transform('remove-empty-catch-blocks');
  });
});
